sudo: required
dist: trusty
language: python
matrix:
  include:
    - env: TOXENV=py26
    - env: TOXENV=py27
    - env: TOXENV=py34
    - env: TOXENV=py35
    - env: TOXENV=py36
    - env: TOXENV=py37
      dist: xenial
    - env: TOXENV=pypy
install:
  - scripts/travis.sh
  - make install
  - pip-accel install coveralls tox
  - pip-accel install -r requirements-checks.txt
script:
  - make check
  - make tox
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
